# Generated by Django 5.0.4 on 2024-04-27 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0002_camp_latitude_camp_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='camps.camp')),
            ],
        ),
    ]
