# Generated by Django 5.0.4 on 2024-04-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_campimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='campimage',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='campimage',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
