# Generated by Django 5.0.4 on 2024-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_remove_campimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campimage',
            name='image',
            field=models.ImageField(upload_to='images/camps/'),
        ),
    ]
