# Generated by Django 5.0.4 on 2024-05-04 08:30

import api.camps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0006_campoccupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='campfeature',
            name='description',
            field=models.TextField(default=1, max_length=1024, validators=[api.camps.models.validate_description]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
