# Generated by Django 5.0.4 on 2024-05-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0007_campfeature_description_alter_campimage_alt_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campfeature',
            options={'verbose_name': 'Camp Feature', 'verbose_name_plural': 'Camp Features'},
        ),
        migrations.AlterModelOptions(
            name='campimage',
            options={'verbose_name': 'Camp Image', 'verbose_name_plural': 'Camp Images'},
        ),
        migrations.AlterModelOptions(
            name='campoccupancy',
            options={'verbose_name': 'Camp Occupancy', 'verbose_name_plural': 'Camp Occupancies'},
        ),
    ]
