# Generated by Django 5.0.4 on 2024-05-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0008_alter_campfeature_options_alter_campimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
