# Generated by Django 5.0.4 on 2024-05-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0009_camp_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='camps.camp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_camps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camp Like',
                'verbose_name_plural': 'Camp Likes',
                'unique_together': {('camp', 'user')},
            },
        ),
    ]
