# Generated by Django 5.0.4 on 2024-04-12 04:49

import api.features.models
import api.tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('CAMP_SITE', 'camp_site'), ('SURROUNDINGS', 'surroundings')], max_length=100)),
                ('label', models.CharField(db_index=True, max_length=100, unique=True, validators=[api.tags.models.validate_label])),
                ('description', models.TextField(blank=True, max_length=1000, validators=[api.features.models.validate_description])),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['feature_type', 'label'],
            },
        ),
    ]
