# Generated by Django 5.0.4 on 2024-04-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('CAMP_SITE', 'camp_site'), ('SURROUNDINGS', 'surroundings')], max_length=20),
        ),
    ]
