# Generated by Django 5.0.4 on 2024-05-04 06:09

import api.features.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_feature_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(max_length=1024, validators=[api.features.models.validate_description]),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('HIGHLIGHT', 'highlight'), ('SURROUNDING', 'surrounding'), ('ACTIVITY', 'activity')], max_length=32),
        ),
        migrations.AlterField(
            model_name='feature',
            name='label',
            field=models.CharField(db_index=True, max_length=128, unique=True, validators=[api.features.models.validate_label]),
        ),
    ]
