# Generated by Django 5.0.4 on 2024-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_alter_feature_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('highlight', 'highlight'), ('surrounding', 'surrounding'), ('activity', 'activity')], max_length=32),
        ),
    ]
