# Generated by Django 5.0.6 on 2024-05-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
