# Generated by Django 5.0.6 on 2024-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Processing', 'Processing'), ('Requires Action', 'Requires Action'), ('Requires Capture', 'Requires Capture'), ('Requires Confirmation', 'Requires Confirmation'), ('Requires Payment Method', 'Requires Payment Method'), ('Succeeded', 'Succeeded')], default='Processing', max_length=64),
        ),
    ]
