# Generated by Django 5.0.6 on 2024-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_payment_id_order_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='booking_status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Pending', 'Pending'), ('Fullfilled', 'Fullfilled')], default='Pending', max_length=64),
        ),
    ]
